---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install dependencies.
  package:
    name: nano
    state: present

- name: Clone the Singularity Registry Server Git repo
  git:
    repo: https://github.com/singularityhub/sregistry
    dest: /opt/sregistry/
