---
- name: Converge
  hosts: all
  become: true

  vars:
    docker_install_compose: false
    pip_install_packages:
      - name: docker
      - name: docker-compose
    nginx_service_state: stopped

  pre_tasks:
    - include_tasks: environment-prep.yml

  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == 'RedHat'
    - geerlingguy.git
    - geerlingguy.pip
    - geerlingguy.docker
    - geerlingguy.nginx
    - zorlin.sregistry
