---
# This playbook is used to execute Ansible tests.
# It may also be useful for testing Ansible features while developing (but that's a hack...)

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: list python version
      command: "python --version"
      register: test_python_version
      changed_when: false

    - name: output requested information
      debug:
        msg:
          - "python version is {{ test_python_version.stdout }}"
