---
# This playbook is used to execute Ansible tests.
# It may also be useful for testing Ansible features while developing (but that's a hack...)

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
    - name: list python version
      command: "python --version"
      register: test_python_version
      changed_when: false

    - name: dump facts
      setup:
      register: test_facts

    - name: output requested information
      debug:
        msg:
          - "python version is {{ test_python_version.stderr }}"
          - "ansible python version is {{ ansible_python.version.major }}"
          - "{{ ansible_python.version.major == 2 }}"
